# Generated by Django 5.1.7 on 2025-03-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_db', '0002_alter_userprofil_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
