# Generated by Django 5.1.7 on 2025-03-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_db', '0005_alter_offer_image_alter_offer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='offer',
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
