# Generated by Django 5.1.7 on 2025-03-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_db', '0009_remove_order_features_remove_order_offer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='business_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_details', to='coderr_db.userprofil'),
        ),
    ]
