# Generated by Django 5.1.7 on 2025-03-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_db', '0010_alter_offerdetail_business_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], max_length=10),
        ),
    ]
