# Generated by Django 5.1.7 on 2025-03-28 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_db', '0011_alter_order_status_alter_userprofil_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='coderr_db.userprofil'),
        ),
    ]
