# Generated by Django 5.1.7 on 2025-03-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_db', '0012_alter_review_reviewer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseInfo',
        ),
    ]
