# Generated by Django 5.1.7 on 2025-03-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_db', '0013_delete_baseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.FileField(blank=True, max_length=99, null=True, upload_to='images/'),
        ),
    ]
