# Generated by Django 5.1.7 on 2025-03-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_db', '0014_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='file',
            field=models.FileField(blank=True, max_length=99, upload_to='images/'),
        ),
    ]
