# Generated by Django 5.1.7 on 2025-04-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_db', '0015_alter_userprofil_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofil',
            name='username',
        ),
        migrations.AddField(
            model_name='offer',
            name='min_delivery_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='tel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
